/** @type {import('tailwindcss').Config} */
const colors = require("tailwindcss/colors");
const {
  toRGB,
  withOpacityValue,
} = require("./src/assets/theme/js/tailwind-config-helper.js");

module.exports = {
  content: [
    "./src/**/*.{html,ts}",
    "./node_modules/@left4code/tw-starter/**/*.js",
  ],
  darkMode: "class",
  important: true,
  theme: {
    extend: {
      screens: {
        xs: "540px",
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1536px",
      },
      container: {
        center: true,
        padding: {
          DEFAULT: "12px",
          sm: "1rem",
          lg: "45px",
          xl: "5rem",
          "2xl": "13rem",
        },
      },
      colors: {
        rgb: toRGB({
          inherit: colors.inherit,
          current: colors.current,
          transparent: colors.transparent,
          black: colors.black,
          white: colors.white,
          slate: colors.slate,
          gray: colors.gray,
          zinc: colors.zinc,
          neutral: colors.neutral,
          stone: colors.stone,
          red: colors.red,
          orange: colors.orange,
          amber: colors.amber,
          yellow: colors.yellow,
          lime: colors.lime,
          green: colors.green,
          emerald: colors.emerald,
          teal: colors.teal,
          cyan: colors.cyan,
          sky: colors.sky,
          blue: colors.blue,
          indigo: colors.indigo,
          violet: colors.violet,
          purple: colors.purple,
          fuchsia: colors.fuchsia,
          pink: colors.pink,
          rose: colors.rose,
          sky: colors.sky,
          stone: colors.stone,
          neutral: colors.neutral,
          gray: colors.gray,
          slate: colors.slate,
        }),
        primary: {
          light: "rgba(246,141,47,.4)",
          DEFAULT: "#f78e2f",
          dark: "#e77e1f",
          heading: "#f97500",
          1: "#1C3FAA",
          2: "#2e51bb",
          3: "#D32929",
          4: "#91C714",
          5: "#3160D8",
          6: "#F78B00",
          7: "#FBC500",
          8: "#3b5998",
          9: "#4ab3f4",
          10: "#517fa4",
          11: "#0077b5",
        },
        secondary: {
          light: "#3d3d3d",
          DEFAULT: "#444444",
          dark: "#17222d",
          gray: "#f8fafc",
        },
        success: withOpacityValue("--color-success"),
        info: withOpacityValue("--color-info"),
        warning: withOpacityValue("--color-warning"),
        pending: withOpacityValue("--color-pending"),
        danger: withOpacityValue("--color-danger"),
        light: withOpacityValue("--color-light"),
        dark: withOpacityValue("--color-dark"),
        slate: {
          50: withOpacityValue("--color-slate-50"),
          100: withOpacityValue("--color-slate-100"),
          200: withOpacityValue("--color-slate-200"),
          300: withOpacityValue("--color-slate-300"),
          400: withOpacityValue("--color-slate-400"),
          500: withOpacityValue("--color-slate-500"),
          600: withOpacityValue("--color-slate-600"),
          700: withOpacityValue("--color-slate-700"),
          800: withOpacityValue("--color-slate-800"),
          900: withOpacityValue("--color-slate-900"),
        },
        darkmode: {
          50: withOpacityValue("--color-darkmode-50"),
          100: withOpacityValue("--color-darkmode-100"),
          200: withOpacityValue("--color-darkmode-200"),
          300: withOpacityValue("--color-darkmode-300"),
          400: withOpacityValue("--color-darkmode-400"),
          500: withOpacityValue("--color-darkmode-500"),
          600: withOpacityValue("--color-darkmode-600"),
          700: withOpacityValue("--color-darkmode-700"),
          800: withOpacityValue("--color-darkmode-800"),
          900: withOpacityValue("--color-darkmode-900"),
        },
        other: {
          light: "#e2dcd9",
          "cart-light": "#e5e5e5",
          gray: "#8d9296",
          blue: "#2fb5f6",
          red: "#ff0007",
        },
        theme: {
          1: "#8ec63f",
          2: "#F1F5F8",
          3: "#8ec63f",
          4: "#8ec63f",
          5: "#DEE7EF",
          6: "#D32929",
          7: "#365A74",
          8: "#D2DFEA",
          9: "#91C714",
          10: "#8ec63f",
          11: "#F78B00",
          12: "#FBC500",
          13: "#7F9EB9",
          14: "#E6F3FF",
          15: "#8DA9BE",
          16: "#607F96",
          17: "#FFEFD9",
          18: "#D8F8BC",
          19: "#8ec63f",
          20: "#8ec63f",
          21: "#C6D4FD",
          22: "#E8EEFF",
          23: "#8ec63f",
          24: "#8ec63f",
          25: "#C7D2FF",
          26: "#8ec63f",
          27: "#8ec63f",
          28: "#BBC8FD",
          29: "#8ec63f",
          30: "#98AFF5",
        },
        white: "white",
        black: "black",
        current: "current",
        transparent: "transparent",
        dark: {
          1: "#293145",
          2: "#232a3b",
          3: "#313a55",
          4: "#1e2533",
          5: "#3f4865",
          6: "#2b3348",
          7: "#181f29",
        },
        gray: {
          100: "#f7fafc",
          200: "#edf2f7",
          300: "#e2e8f0",
          400: "#cbd5e0",
          500: "#a0aec0",
          600: "#718096",
          700: "#4a5568",
          800: "#2d3748",
          900: "#1a202c",
        },
      },
      fontFamily: {
        roboto: ["Roboto"],
        montserrat: ["Montserrat", "serif"],
        playfairDisplay: ["Playfair Display", "serif"],
        atcripley: ["ATC Ripley", "sans-serif"],
        poppins: ["Poppins", "sans-serif"],
      },
      boxShadow: {
        sm: "0 2px 4px 0 rgb(60 72 88 / 0.15)",
        DEFAULT: "0 0 3px rgb(60 72 88 / 0.15)",
        md: "0 5px 13px rgb(60 72 88 / 0.20)",
        lg: "0 10px 25px -3px rgb(60 72 88 / 0.15)",
        xl: "0 20px 25px -5px rgb(60 72 88 / 0.1), 0 8px 10px -6px rgb(60 72 88 / 0.1)",
        "2xl": "0 25px 50px -12px rgb(60 72 88 / 0.25)",
        inner: "inset 0 2px 4px 0 rgb(60 72 88 / 0.05)",
        cart: "0 15px 60px rgb(0 0 0 / 8%)",
      },
      zIndex: {
        1: "1",
        2: "2",
        3: "3",
        999: "999",
      },
      backgroundImage: {
        "client-banner": "url('/assets/images/banner-bg.svg')",
      },
      maxWidth: {
        "1/4": "25%",
        "1/2": "50%",
        "3/4": "75%",
      },
      strokeWidth: {
        0.5: 0.5,
        1.5: 1.5,
        2.5: 2.5,
      },
    },
  },
  variants: {
    extend: {
      boxShadow: ["dark"],
    },
  },
  plugins: [
    require("@tailwindcss/typography"),
    require("@tailwindcss/forms"),
    require("@tailwindcss/aspect-ratio"),
  ],
};
